FROM node:16
WORKDIR /app

# Copiar package.json primero
COPY package*.json ./
RUN npm install

# Copiar el script wrapper
COPY app-dev-wrapper.sh ./
RUN chmod +x ./app-dev-wrapper.sh

# Puerto que expondrá la aplicación
EXPOSE 3000

# CAMBIO AQUÍ: Ejecutar con shell en lugar de con Node.js
CMD ["/bin/sh", "./app-dev-wrapper.sh"]
